flowchart TD
    IO0[/"text write<br/>n=4"/]
    IO1[("text read<br/>n=4")]
    IO2[/"json write<br/>n=3"/]
    IO3[("json read<br/>n=2")]
    IO4[("yaml read<br/>n=1")]
    IO5[/"yaml write<br/>n=1"/]
    NET6("Network I/O<br/>n=1")
