graph TB
    subgraph feature["Feature Packages"]
        P0["azlin<br/>2 files<br/>I=0.00"]
    end

    subgraph leaf["Leaf Packages"]
        P1["cli_documentation<br/>8 files<br/>I=1.00"]
    end


    click P0 "../service-components/" "View details"
