graph LR
    subgraph ext["External Dependencies"]
        E0["tokio<br/>imports: 0"]
        E1["serde<br/>imports: 0"]
        E2["serde_json<br/>imports: 0"]
        E3["serde_yaml<br/>imports: 0"]
        E4["toml<br/>imports: 0"]
        E5["clap<br/>imports: 0"]
        E6["clap_complete<br/>imports: 0"]
        E7["indicatif<br/>imports: 0"]
        E8["dialoguer<br/>imports: 0"]
        E9["console<br/>imports: 0"]
        E10["ratatui<br/>imports: 0"]
        E11["crossterm<br/>imports: 0"]
        E12["azure_identity<br/>imports: 0"]
        E13["azure_core<br/>imports: 0"]
        E14["azure_mgmt_compute<br/>imports: 0"]
        E15["azure_mgmt_network<br/>imports: 0"]
        E16["azure_mgmt_resources<br/>imports: 0"]
        E17["azure_mgmt_storage<br/>imports: 0"]
        E18["azure_security_keyvault_secrets<br/>imports: 0"]
        E19["azure_mgmt_costmanagement<br/>imports: 0"]
    end

    subgraph int["Internal Packages"]
        P0["benchmark_parallel_vm_list"]
        P1["benchmark_vm_list"]
        P2["audit_key_operations"]
        P3["cli_documentation"]
        P4["example_manager"]
        P5["extractor"]
        P6["generator"]
        P7["hasher"]
        P8["models"]
        P9["sync_manager"]
        P10["validator"]
        P11["doc_sync"]
        P12["extract_help"]
        P13["generate_docs"]
        P14["test_audit_key_operations"]
        P15["validate_documentation"]
        P16["azlin"]
        P17["rust_bridge"]
    end

    click P0 "../compile-deps/" "View compile deps"
